---
title: "Untitled"
output:
  pdf_document: default
  html_document: default
---

ref: http://www.sthda.com/english/articles/31-principal-component-methods-in-r-practical-guide/118-principal-component-analysis-in-r-prcomp-vs-princomp/

```{r}
library(factoextra)
decathlon2.active <-read.csv('../data/select_table.txt',sep = ',',row.names = 1)
head(decathlon2.active)
```

```{r}
res.pca <- princomp(decathlon2.active, scale = TRUE,cor=FALSE)
summary(res.pca,loadings=TRUE)
```



```{r}
res.pca.loadings<-loadings(res.pca)
res.pca.loadings
```


```{r}
fviz_eig(res.pca)
```


```{r}
pdf( "../output/variance_explained.pdf", width = 6, height = 4 )
fviz_eig(res.pca)
```

```{r}
 fviz_pca_ind(res.pca,
             col.ind = "cos2", # Color by the quality of representation
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),
             repel = TRUE     # Avoid text overlapping
             )
```


```{r}
pdf( "../output/fviz_pca_ind.pdf", width = 10, height = 10 )
fviz_pca_ind(res.pca,
             col.ind = "cos2", # Color by the quality of representation
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),
             repel = TRUE     # Avoid text overlapping
             )
```



```{r}
fviz_pca_var(res.pca,
             col.var = "contrib", # Color by contributions to the PC
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),
             repel = TRUE     # Avoid text overlapping
             )
```

```{r}
pdf( "../output/fviz_pca_var.pdf", width = 6, height = 6 )
fviz_pca_var(res.pca,
             col.var = "contrib", # Color by contributions to the PC
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),
             repel = TRUE     # Avoid text overlapping
             )
```


```{r}
fviz_pca_biplot(res.pca, repel = TRUE,
                col.var = "#2E9FDF", # Variables color
                col.ind = "#696969"  # Individuals color
                )
```

```{r}
pdf( "../output/fviz_pca_biplot.pdf", width = 10, height = 10)
fviz_pca_biplot(res.pca, repel = TRUE,
                col.var = "#2E9FDF", # Variables color
                col.ind = "#696969"  # Individuals color
                )
```


```{r}
# Eigenvalues
eig.val <- get_eigenvalue(res.pca)
eig.val
  
# Results for Variables
res.var <- get_pca_var(res.pca)
res.var$coord          # Coordinates
res.var$contrib        # Contributions to the PCs
res.var$cos2           # Quality of representation 
# Results for individuals
res.ind <- get_pca_ind(res.pca)
res.ind$coord          # Coordinates
res.ind$contrib        # Contributions to the PCs
res.ind$cos2           # Quality of representation 
```


```{r}

```


```{r}

```


```{r}

```


```{r}

```





