---
title: "Untitled"
output:
  pdf_document: default
---

# References:
- a overall R package could be used to do estimition, plot...
see details in their paper, example section: 
    - https://www.jstatsoft.org/article/view/v036i01/v36i01.pdf
    - https://rdrr.io/rforge/termstrc/man/
    - https://github.com/datarob/termstrc/tree/6b0701efa06776083285c5a74f17edbf1a656e0f/R
    - https://github.com/datarob/termstrc/tree/6b0701efa06776083285c5a74f17edbf1a656e0f/demo

```{r}
#installation: 
#library(devtools)
#install_github("datarob/termstrc")
# select install them all (number 13), install from source: yes
library('termstrc')
```


```{r}
oldpar <- par(no.readonly = TRUE)

data(govbonds)

ns_res <- estim_nss(govbonds, c("GERMANY", "AUSTRIA", "FRANCE"),matrange = c(0,30), method = "ns", tauconstr = list(c(0.2,5,0.1),c(0.2,5,0.1), c(0.2,5,0.1)))

print(ns_res)
plot(ns_res)
summary(ns_res)

## Plot startparameter grid search results
par(mfrow=c(1,3))
plot(ns_res$spsearch$GERMANY,main="GERMANY")
plot(ns_res$spsearch$AUSTRIA,main="AUSTRIA")
plot(ns_res$spsearch$FRANCE,main="FRANCE")

## Plot all yield curves in one figure
par(mfrow=c(1,1))
plot(ns_res,multiple=TRUE)

par(oldpar)


```

```{r}
oldpar <- par(no.readonly = TRUE)

data(datadyncouponbonds)

## Diebold/Li estimation
dl_res <- estim_nss(datadyncouponbonds, c("GERMANY"), method = "dl", lambda = 1/3)

## 3d yield curve plot
plot(dl_res)

## Estimated parameters
plot(param(dl_res))
summary(param(dl_res))

## Estimate Nelson/Siegel model
ns_res <- estim_nss(datadyncouponbonds, c("GERMANY"), method = "ns", tauconstr = list(c(0.2, 7, 0.2)), optimtype = "allglobal")

## Estimated parameters
plot(param(ns_res))
summary(param(ns_res))

## Estimate Svensson model
sv_res <- estim_nss(datadyncouponbonds, c("GERMANY"), method = "sv",tauconstr = list(c(0.2,7,0.2,0.5)))

## Plot start parameter grid search for t=1

## Estimated parameters
plot(param(sv_res))
summary(param(sv_res))

## Estimate Adjusted Svensson model
asv_res <- estim_nss(datadyncouponbonds, c("GERMANY"), method = "asv",tauconstr = list(c(0.2,10,0.2)))

## Estimated parameters
plot(param(asv_res))
summary(param(asv_res))


## Factor contributions at t=1
par(mfrow=c(2,2))
fcontrib(param(dl_res), index = 1, method="dl")
fcontrib(param(ns_res), index = 1, method="ns")
fcontrib(param(sv_res), index = 1, method="sv")
fcontrib(param(asv_res), index = 1, method="asv")



## Compare GOF
allgof <- cbind(summary(dl_res)$gof, summary(ns_res)$gof, summary(sv_res)$gof, summary(asv_res)$gof)
colnames(allgof) <- c("Diebold/Li", "Nelson/Siegel", "Svensson", "Adj. Svensson")
print(allgof)

par(oldpar)
```

